root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_delim = " "
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/app"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor", "test"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  poll_interval = 500 # ms
  stop_on_error = true

[color]
  app = "green"
  build = "yellow"
  main = "blue"
  runner = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true 