apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-starter
  labels:
    app: go-rest-starter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-rest-starter
  template:
    metadata:
      labels:
        app: go-rest-starter
    spec:
      containers:
      - name: go-rest-starter
        image: your-registry/go-rest-starter:latest
        ports:
        - containerPort: 7001
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: go-rest-starter-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: go-rest-starter-config
              key: db_port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: go-rest-starter-secrets
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-rest-starter-secrets
              key: db_password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: go-rest-starter-config
              key: db_name
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: go-rest-starter-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: go-rest-starter-config
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-rest-starter-secrets
              key: redis_password
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-starter
spec:
  selector:
    app: go-rest-starter
  ports:
  - port: 80
    targetPort: 7001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-rest-starter-config
data:
  db_host: "postgres"
  db_port: "5432"
  db_name: "restapi"
  redis_host: "redis"
  redis_port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: go-rest-starter-secrets
type: Opaque
data:
  db_username: cG9zdGdyZXM=  # postgres (base64编码)
  db_password: cG9zdGdyZXM=  # postgres (base64编码)
  redis_password: ""  # 空密码 (base64编码)
