app:
  server:
    port: ${PORT:8080}          # 使用环境变量，默认8080
    timeout: 30s
    read_timeout: 15s
    write_timeout: 15s

  database:
    driver: postgres
    host: ${DB_HOST}            # 从环境变量读取
    port: ${DB_PORT:5432}       
    username: ${DB_USER}
    password: ${DB_PASSWORD}    # 敏感信息必须从环境变量读取
    dbname: ${DB_NAME}
    sslmode: ${DB_SSL_MODE:require}  # 生产环境建议启用SSL
    max_open_conns: 100         # 生产环境增加连接池大小
    max_idle_conns: 25
    conn_max_lifetime: 30m      # 缩短连接生命周期，避免长连接问题

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD} 
    db: ${REDIS_DB:0}

  log:
    level: ${LOG_LEVEL:info}    # 生产环境默认info级别
    file: ${LOG_FILE:logs/app.log}
    console: ${LOG_CONSOLE:false}  # 生产环境默认不输出到控制台

  jwt:
    secret: ${JWT_SECRET}        # 必须从环境变量读取
    access_token_exp: ${JWT_ACCESS_EXP:2h}   # 生产环境缩短token有效期
    refresh_token_exp: ${JWT_REFRESH_EXP:72h}
    issuer: ${JWT_ISSUER:go-rest-starter}